on:
 workflow_call:  

jobs:
  echo-inside-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST env var
        run: echo "TEST=${{vars.TEST}}" >> $GITHUB_ENV

  echo-inside-test-123:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST env var
        run: |
          echo "$TEST"

  call-codeql-workflow:
    uses: ./.github/workflows/output.yml

  use-app-version:
    needs: call-codeql-workflow
    uses: ./.github/workflows/app-version.yml
    with:
      app_version: ${{ needs.call-codeql-workflow.outputs.app_version }}


  write_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
    - name: Write GitHub context to log
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Write job context to log
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    # this errors out if you try to access it w/o using a reusable workflow
    # - name: Write jobs context to log (reusable workflows)
    #   env:
    #     JOB_CONTEXT: ${{ toJSON(jobs) }}
    #   run: echo "$JOBS_CONTEXT"
    - name: Write steps context to log
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Write runner context to log
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Write strategy context to log
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Write matrix context to log
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Write env context to log
      env:
        ENV_CONTEXT: ${{ toJSON(env) }}
      run: |
        echo "TEST:${{ vars.TEST }}" >> $GITHUB_ENV
        echo "$ENV_CONTEXT"

    - name: Write secrets context to log
      env:
        SECRETS_CONTEXT: ${{ toJSON(secrets) }}
      run: |
        echo "$TEST"
        "${{ toJSON(secrets) }} "
        echo echo "SECRETS_CONTEXT=$(echo '${{ toJSON(secrets) }}' | jq -c .)" >> $GITHUB_ENV

    - name: Echo secret
      run: echo "$SECRETS_CONTEXT"