on:
 workflow_call:  

jobs:
  echo-inside-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST env var
        run:
          echo "TEST inside is ${{ vars.TEST }}"

  call-codeql-workflow:
    uses: ./.github/workflows/output.yml

  use-app-version:
    needs: call-codeql-workflow
    uses: ./.github/workflows/app-version.yml
    with:
      app_version: ${{ needs.call-codeql-workflow.outputs.app_version }}