name: Main Workflow

on:
  workflow_dispatch:

env:
  TEST: ${{ vars.TEST }}

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST env var
        run:
          echo "TEST is $TEST"
    env:
      TEST: ${{ vars.TEST }}

  test:
    uses: ./.github/workflows/main2.yml  # Update with actual org/repo and branch

