name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-codeql-workflow:
    runs-on: ubuntu-latest
    name: Version
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/main2.yml  


