name: Reusable CodeQL Workflow

on:
  workflow_call:
    inputs:
      java_version:
        description: "Java version to use"
        required: false
        default: "17"
        type: string
      codeql_queries:
        description: "CodeQL queries to use"
        required: false
        default: "security-extended"
        type: string
    secrets:
      maven_credentials:
        description: "Maven credentials if needed"
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      java_version: ${{ inputs.java_version }}
    secrets:
      maven_credentials: ${{ secrets.maven_credentials }}

  codeql-analysis:
    name: Java CodeQL Analysis
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          debug: true
          languages: "java"
          queries: ${{ inputs.codeql_queries }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          queries: ${{ inputs.codeql_queries }}
